HF_TOKEN = "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"
GEMINI_API_KEY = "AIzaSyAmCXZC0h9Dk0Mfo7TeZJG843tjMYdnagA"
OPENAI_API_KEY = "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"

